version: '3'
services:
  web:
    image: nodejs-app:1.4.1
    ports:
      - '5000:3000' # Map your container's port 3000 to your host's port 5000
    volumes:
      - .:/app # Mount your local code directory into the container at /app
    depends_on:
      - phpmyadmin

  mysql:
    image: mysql:5.7.42
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # Change this to your desired root password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  # PHPMyAdmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 'mysql'
      PMA_PORT: '3306'
      MYSQL_ROOT_PASSWORD: 'root' # Use the same root password as in the MySQL container
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
